# Application Configuration
spring.application.name=dbxf

# Enable the H2 Web Console for visual database inspection
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 In-Memory Database Connection Settings
spring.datasource.url=jdbc:h2:mem:dbxfdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=mike
spring.datasource.password=